### ISSUE TITLE
AttributeError: 'Trainer' object has no attribute 'X_interior'

### ISSUE THREAD

**Issue by hassaniqbal209** [sloooWTYK/GF-Net#1]
Hi, I get the following error when running the first command on the readme file. Any suggestions on how to resolve this? Thank you in advance. 

python ./trainer.py --pde_case Poisson --domain_type square --blocks_num 4 
4 --z_coarse_num 545 --x_coarse_num 2105 --x_middle_num 8265 --x_refine_num 32753 --scale 5 10 --epochs_Adam 20000 --epochs_LBFGS 10000 --tol 1e-4 --cuda_index 0
****************************** Infos of Trainset ******************************
x info: coarse - 2105,  middle - 8265,  refine - 32753
z info: 16 - [27, 31, 31, 27, 31, 37, 37, 31, 31, 37, 37, 31, 27, 31, 31, 27], total - 504
********************************************************************************

****************************** Infos of Validset ******************************
x info: interior - 1953,  boundary - 152
z info: [-0.7256755  -0.72584677]
********************************************************************************

Start Trainning (blocks #0)
Traceback (most recent call last):
  File "\GF-Net-main\trainer.py", line 468, in <module>
    trainer.train()
  File "\GF-Net-main\trainer.py", line 103, in train
    self.train_block(k)
  File "\GF-Net-main\trainer.py", line 172, in train_block
    train_loss, train_loss_interior, train_loss_symmetry, train_loss_boundary = self.train_Adam(epoch)
  File "\GF-Net-main\trainer.py", line 265, in train_Adam
    res, res_symmetry, u_boundary_pred = self.pinn(self.X_interior, self.X_boundary)
AttributeError: 'Trainer' object has no attribute 'X_interior'

**Comment by sloooWTYK** [comment]
Do you have CUDA and Nvidia GPU available?

**Comment by hassaniqbal209** [comment]
Yes, I tried with another device with CUDA/Nvidia GPU available and its running now. Thank you for the advice.
